title:             Yangseas Blog
email:             yangseas@qq.com
description:       完美生活 至爱音乐
author:            Yang Jin
baseurl:           ""
url:               "http://yangseas.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   yangseas
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
