# Site settings
title:             Yangseas Blog
email:             yangseas@qq.com
description:       完美生活 至爱音乐
author:            Yang Jin
baseurl:           ""
url:               "http://yangseas.github.io"

# SNS settings
weibo_name: YJTTII
zhihu_name:  niexia
github_username:   yangseas

# Building settings
highlighter: rouge
paginate: 10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
