# Site settings
title:             Yangseas Blog        #标题
email:             yangseas@qq.com      #联系邮箱
description:       完美生活 至爱音乐     
author:            Yang Jin             
baseurl:           ""
url:               "http://yangseas.github.io"

# SNS settings  你可能不清楚你的name具体指什么?先点击我的连接参考
weibo_name: YJTTII                      #微博
zhihu_name:  niexia                     #知乎
github_username:   yangseas             #github

# Building settings
highlighter: rouge
paginate: 10
paginate_path:  "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# HOME lists
listCount: 8                            # 首页展示几篇